# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'about',   url: ''}
- {name: 'resume', url: 'resume.html'}
- {name: 'writing', url: 'writing.html'}
# - {name: 'Contact', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/simicvm'}
- {icon: 'twitter',    link: 'https://twitter.com/simicvm'}
- {icon: 'linkedin',   link: 'http://www.linkedin.com/in/simicvm/'}
- {icon: 'medium',     link: 'https://medium.com/@simicvm'}
- {icon: 'envelope',   link: 'mailto:simicvm@gmail.com'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
